name: push_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  equatable: ^2.0.5
  firebase_messaging: ^14.7.16
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  go_router: ^13.2.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
